### ISSUE TITLE
Create 'test/java' subdirectory in 'src' directory 

### ISSUE THREAD

**Issue by vlad-nitu** [GDcheeriosYT/gentrys-quest#56]
According to best practices, all test classes should be kept in 'test/java' subdirectory, instead of directly creating a 'test' subdirectory in 'main/java'. 

The **changes** that I would like to address **in this issue** are the following: 
- Refactor such that the 'test' subdirectory is in the correct place. This would help other open-source contributors to easily comprehend the code and to work on #55.
-  Change the name of 'CharacterInfo.java' class to 'CharacterTest.java', as all test classes should end in "Test"

## Future improvements
- 'CharacterTest.java' class (previously named 'CharacterInfo.java') is currently not properly testing anything (as it just prints,  instead of asserting specific behavior using Testing frameworks i.e: JUnit). I'll come up with an example of how I would test 'Enemy.java' class, and if this suits the contributors of this project feel free to approve the PR and also 'inspire' from there in order to test 'Character.java' class in a similar way.

**Comment by GDcheeriosYT** [comment]
I will say, as I am only in highschool, we have never gone over unit testing. I am not really familliar with unit testing so I was generally looking at just making tests for things that take time. For example: as you(the player) progress I want to ensure that things scale properly. So I will just add simple "scene" testing I guess you can call it. Lets say for example I am going to test different stats in a battle, I can make a test battle scene where I can modify anything that will effect  the battle. Like maybe player star rating and have it recalculate all stats according to the new star rating.

**Comment by vlad-nitu** [comment]
I get your idea, however I won't classify this type of simulating behavior  of your program as "testing", but I think it is a good way to start exploring your functionallity.
After that, you may want to do some unit testing, as this is the easiest way to test your program (having some drawbacks compared to integration testing, end-to-end testing and so on).
I would recommend going through Baeldung's JUnit testing framework tutorials (at least this is how I started before having a dedicated uni course on testing). Here's the link: https://www.baeldung.com/junit
In addition, I'll also leave the name of the book I studied for the 'Software Quality and Testing' course I had at university: _Software Testing: A Developer's Guide book, by [Maurício Aniche](https://www.mauricioaniche.com/)._ (on our teacher's link which you can click you can find the link to buy the book if you're interested in the "[Effective Software Testing](https://www.effective-software-testing.com/)" subsection.)  I'm not sure if there's an online version of the book at the moment)

**Comment by GDcheeriosYT** [comment]
Ok, I appreciate it!
